<!DOCTYPE html>
<html lang="<?php echo \Orange\Portal\Core\App\Portal::$sitelang; ?>" xml:lang="<?php echo \Orange\Portal\Core\App\Portal::$sitelang; ?>" xmlns="http://www.w3.org/1999/xhtml">
	<head><?php
			if (in_array(2,\Orange\Portal\Core\App\Portal::getInstance()->user->get('user_groups'))){
				\Orange\Portal\Core\App\Theme::addStyleFile('themes/orange2016/static/admin-front.css');
			}
			\Orange\Portal\Core\App\Theme::addStyleFile('themes/default/static/system.css');
			\Orange\Portal\Core\App\Theme::addStyleFile('themes/orange2016/static/style.css');
			echo $portal->blockDirect('system/system/head');
		?>
        <meta name="viewport" content="width=device-width" />
    </head>
	<body>
        <div id="header-wrapper">
            <?php echo $portal->blocksArea('header','<header>','</header>'); ?>
        </div>
        <?php echo $portal->blocksArea('sub-header','<section id="sub-header">','</section>'); ?>
        <div id="content-wrapper">
        <?php $aside = $portal->blocksArea('column','<aside>','</aside>'); ?>
		<section id="body" <?php echo strlen($aside) ? 'class="with-aside"' : ''; ?>><?php echo $this->fetch($this->theme->getContentTemplate($content), ['content' => $content, 'response' => $response]); ?></section>
		<?php if (strlen($aside)){ echo $aside; } ?>
        </div>
        <?php echo $portal->blocksArea('footer','<footer>','</footer>'); ?>
	</body>
</html>