<?php if (count($languages) > 1){ ?>
<ul class="lang-switcher">
<?php foreach ($languages as $lang_code => $lang_title){ ?>
	<li><a href="<?php $this->ee(
		isset($pages[$lang_code])
            ? $pages[$lang_code]->getURL($default_lang, $current_lang, $lang_code, $get_string)
            : ( isset($pages[''])
                ? $pages['']->getURL($default_lang, $current_lang, $lang_code, $get_string)
                : OP_WWW.'/'.$lang_code
			)
		); ?>" class="lang-<?php $this->ee($lang_code); ?>" title="<?php $this->ee($lang_title); ?>" style="background-image: url('<?php echo OP_WWW.'/themes/orange2016/static/flags/'.$this->esc($lang_code); ?>.png');"><?php $this->ee($lang_title); ?></a></li>
<?php } ?>
</ul>
<?php } ?>