<table class="op-admin-list-table">
	<thead>
		<tr>
            <th style="width: 20%;"><?php echo OPAL_Lang::t('module_title'); ?></th>
            <th style="width: 50%;"><?php echo OPAL_Lang::t('module_description'); ?></th>
            <th style="width: 15%;"><?php echo OPAL_Lang::t('module_author'); ?></th>
            <th style="width: 15%;"><?php echo OPAL_Lang::t('module_status'); ?></th>
            <th><br/></th>
            <th><br/></th>
		</tr>
	</thead>
	<?php if ($list){ ?>
	<tbody>
    <?php /** @var OPAL_Module $item */
        foreach ($list as $item){ $info = $item->getInfo(); ?>
		<tr>
            <td><strong><?php $this->el($info['title']); ?></strong></td>
            <td><?php $this->el($info['description']); ?></td>
            <td><a href="<?php $this->ee($info['author_url']); ?>"><?php $this->ee($info['author']); ?></a></td>
            <?php if ($item->id){ ?>
                <td><?php $this->el($item->get('module_status') ? OPAL_Lang::t('ADMIN_ENABLED') : OPAL_Lang::t('ADMIN_DISABLED')); ?></td>
                <td class="icon icon-switch">
                    <?php if ($item->id !== 1){ ?>
                        <a href="<?php $this->ee(OP_WWW.'/admin/modules/switch/'.$info['code']); ?>" class="mk-filemanager-switch" title="<?php $this->el('ADMIN_SWITCH'); ?>"><?php $this->el('ADMIN_SWITCH'); ?></a>
                    <?php } ?>
                </td>
                <td class="icon icon-delete">
                    <?php if ($item->id !== 1){ ?>
                        <?php if (!$item->get('module_status')){ ?>
                            <a href="<?php $this->ee(OP_WWW.'/admin/modules/uninstall/'.$info['code']); ?>" class="mk-filemanager-delete" title="<?php $this->el('ADMIN_UNINSTALL'); ?>" onclick="return confirm('<?php $this->el('ADMIN_ARE_YOU_SURE'); ?>');"><?php $this->el('ADMIN_UNINSTALL'); ?></a>
                        <?php } ?>
                    <?php } ?>
                </td>
            <?php } else { ?>
                <td><?php $this->el('ADMIN_MODULES_NOT_INSTALLED'); ?></td>
                <td class="icon icon-add"><a href="<?php $this->ee(OP_WWW.'/admin/modules/install/'.$info['code']); ?>" class="mk-filemanager-install" title="<?php $this->el('ADMIN_INSTALL'); ?>"><?php $this->el('ADMIN_INSTALL'); ?></a></td>
            <?php } ?>
		</tr>
		<?php } ?>
	</tbody>
	<?php } ?>
</table>