<table class="op-admin-list-table">
	<thead>
		<tr>
            <th style="width: 17.5%;"><?php $this->el('module_title'); ?></th>
            <th style="width: 42.5%;"><?php $this->el('module_description'); ?></th>
            <th style="width: 20%;"><?php $this->el('module_author'); ?></th>
            <th style="width: 10%;"><?php $this->el('module_version'); ?></th>
            <th style="width: 10%;"><?php $this->el('module_status'); ?></th>
            <th><br/></th>
            <th><br/></th>
		</tr>
	</thead>
	<?php if ($list){ ?>
	<tbody>
    <?php /** @var \Orange\Portal\Core\App\Module $item */
        foreach ($list as $item){ $info = $item->getInfo(); ?>
		<tr>
            <td><strong><?php $this->el($info['title']); ?></strong></td>
            <td><?php $this->ee($info['description']); ?></td>
            <td><?php
                $a = is_array($info['author']) ? $info['author'] : [$info['author']];
                $au = is_array($info['author_url']) ? $info['author_url'] : [$info['author_url']];
                foreach ($a as $i => $author){
                    if (isset($au[$i])){ ?><a href="<?php $this->ee($au[$i]); ?>"><?php } $this->ee($author); if (isset($au[$i])){ ?></a><?php }
                    echo '<br/>';
                } ?>
            </td>
            <td><?php $this->ee($info['version']); ?></td>
            <?php if ($item->id){ ?>
                <td><?php $this->el($item->get('module_status') ? 'ADMIN_ENABLED' : 'ADMIN_DISABLED'); ?></td>
                <td class="icon icon-switch">
                    <?php if ($item->id !== 1){ ?>
                        <a href="<?php $this->ee(OP_WWW.'/admin/modules/switch/'.$info['code']); ?>" class="mk-filemanager-switch" title="<?php $this->el('ADMIN_SWITCH'); ?>"><?php $this->el('ADMIN_SWITCH'); ?></a>
                    <?php } ?>
                </td>
                <td class="icon icon-delete">
                    <?php if ($item->id !== 1){ ?>
                        <?php if (!$item->get('module_status')){ ?>
                            <a href="<?php $this->ee(OP_WWW.'/admin/modules/uninstall/'.$info['code']); ?>" class="mk-filemanager-delete" title="<?php $this->el('ADMIN_UNINSTALL'); ?>" onclick="return confirm('<?php $this->el('ADMIN_ARE_YOU_SURE'); ?>');"><?php $this->el('ADMIN_UNINSTALL'); ?></a>
                        <?php } ?>
                    <?php } ?>
                </td>
            <?php } else { ?>
                <td><?php $this->el('ADMIN_MODULES_NOT_INSTALLED'); ?></td>
                <td class="icon icon-add"><a href="<?php $this->ee(OP_WWW.'/admin/modules/install/'.$info['code']); ?>" class="mk-filemanager-install" title="<?php $this->el('ADMIN_INSTALL'); ?>"><?php $this->el('ADMIN_INSTALL'); ?></a></td>
            <?php } ?>
		</tr>
		<?php } ?>
	</tbody>
	<?php } ?>
</table>