<div class="form-area-column"><?php echo $add_form->getHTML(); ?></div>
<div class="form-area-main">
    <?php if ($IDs){ ?>
    <ul>
        <?php foreach($IDs as $id){ ?><li>
            <?php
                if ($page = isset($pages[$id]) ? $pages[$id] : null){
                    $page->isEditable(OPAL_Portal::getInstance()->user->get('user_groups'))
                        ? $this->ee($page->get('content_title'))
                        : $this->el('ADMIN_NO_ACCESS_FOR_CONTENT');
                } else {
                    $this->el('ADMIN_PAGE_WAS_DELETED');
                }
            ?> - <a href="<?php echo $url_base; ?>/deletecategory/<?php $this->ee($id); ?>"><?php $this->el('ADMIN_DELETE'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <?php } ?>
</div>