		<title><?php $this->ee($title); ?></title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="generator" content="Orange Portal 6" />
		<meta property="og:title" content="<?php $this->ee($name); ?>" />
<?php if ($description){ ?>
		<meta property="og:description" content="<?php $this->ee($description); ?>" />
		<meta name="description" content="<?php $this->ee($description); ?>" />
<?php } ?>
<?php if ($keywords){ ?>
		<meta name="keywords" content="<?php $this->ee($keywords); ?>" />
<?php } ?>
<?php if ($author){ ?>
		<meta name="author" content="<?php $this->ee($author); ?>" />
<?php } ?>
<?php if ($url){ ?>
		<meta name="original-source" content="<?php $this->ee($url); ?>" />
		<link rel="canonical" href="<?php $this->ee($url); ?>" />
<?php } ?>
<?php if ($alternate){ foreach ($alternate as $alternate_lang => $alternate_page){ if ($alternate_lang && ($alternate_lang !== \Orange\Portal\Core\App\Portal::$sitelang)){ ?>
		<link rel="alternate" href="<?php $this->ee($alternate_page->getURL(\Orange\Portal\Core\App\Portal::config('system_default_lang'))); ?>" hreflang="<?php $this->ee($alternate_lang); ?>" />
<?php }}} ?>
		<meta name="robots" content="<?php echo $hidden ? 'noindex, follow' : 'all'; ?>" />
<?php if ($image){ ?>
		<meta property="og:image" content="<?php $this->ee($image); ?>" />
		<link rel="image_src" href="<?php $this->ee($image); ?>" />
<?php } ?>
<?php if ($channels = $this->theme->getRSSChannels()){ foreach ($channels as $channel_url => $channel_title){ ?>
		<link rel="alternate" type="application/rss+xml" title="<?php $this->ee($channel_title); ?>" href="<?php $this->ee($channel_url); ?>" />
<?php }} ?>
<?php if ($styles){ foreach ($styles as $file){
	$ext = explode('.',$file);
	$ext = array_pop($ext);
	if ($ext == 'less'){ ?>
		<link rel="stylesheet/less" href="<?php $this->ee($file); ?>" type="text/css" />
	<?php } else { ?>
		<link rel="stylesheet" href="<?php $this->ee($file); ?>" type="text/css" />
<?php } ?>
<?php }} ?>
<?php if ($scripts){ foreach ($scripts as $file){ ?>
		<script type="text/javascript" src="<?php $this->ee($file); ?>"></script>
<?php }} ?>
<?php if ($png_icon){ ?>
	<link rel="icon" href="<?php echo OP_WWW.'/favicon.png'; ?>" />
<?php } else { ?>
	<link rel="shortcut icon" href="<?php echo OP_WWW.'/favicon.ico'; ?>" />
<?php } ?>