<!DOCTYPE html>
<html lang="<?php echo \Orange\Portal\Core\App\Portal::$sitelang; ?>" xml:lang="<?php echo \Orange\Portal\Core\App\Portal::$sitelang; ?>" xmlns="http://www.w3.org/1999/xhtml">
	<head><?php
			if (in_array(2,\Orange\Portal\Core\App\Portal::getInstance()->user->get('user_groups'))){
				\Orange\Portal\Core\App\Theme::addStyleFile('modules/system/static/css/admin-front.css');
			}
			\Orange\Portal\Core\App\Theme::addStyleFile('themes/default/static/system.css');
			\Orange\Portal\Core\App\Theme::addStyleFile('themes/default/static/style.css');
			echo $portal->blockDirect('system/system/head');
		?>
	</head>
	<body>
		<?php echo $portal->blocksArea('header','<header>','</header>'); ?>
		<?php echo $portal->blocksArea('sub-header','<section id="sub-header">','</section>'); ?>
		<?php echo $portal->blocksArea('top-section','<section id="top-section">','</section>'); ?>
		<?php echo $portal->blocksArea('column','<aside>','</aside>'); ?>
		<section id="body"><?php echo $this->fetch($this->theme->getContentTemplate($content), ['content' => $content, 'response' => $response]); ?></section>
		<?php echo $portal->blocksArea('footer','<footer>','</footer>'); ?>
	</body>
</html>