<!DOCTYPE html>
<html>
	<head>
		<title>Orange.Portal 6</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="generator" content="Orange Portal 6" />
		<meta name="robots" content="noindex,nofollow" />
		<link rel="stylesheet" href="<?php echo OP_WWW . '/modules/system/static/css/installer.css'; ?>" type="text/css" />
		<link rel="icon" href="<?php echo OP_WWW; ?>/favicon.png" />
		<meta name="viewport" content="width=device-width" />
	</head>
	<body>
		<header><?php $this->ee($content->get('content_title')); ?></header>
		<section>
			<?php echo $response; ?>
		</section>
	</body>
</html>