<!DOCTYPE html>
<html lang="<?php echo OPAL_Portal::$sitelang; ?>" xml:lang="<?php echo OPAL_Portal::$sitelang; ?>" xmlns="http://www.w3.org/1999/xhtml">
	<head><?php
			if (in_array(2,OPAL_Portal::getInstance()->user->get('user_groups'))){
				OPAL_Theme::addStyleFile('modules/system/static/css/admin-front.css');
			}
			OPAL_Theme::addStyleFile('themes/default/static/system.css');
			OPAL_Theme::addStyleFile('themes/default/static/style.css');
			echo $this->fetch('head.phtml', ['content' => $content]);
		?>
	</head>
	<body>
		<?php echo $portal->blocksArea('header','<header>','</header>'); ?>
		<?php echo $portal->blocksArea('sub-header','<section id="sub-header">','</section>'); ?>
		<?php echo $portal->blocksArea('top-section','<section id="top-section">','</section>'); ?>
		<?php echo $portal->blocksArea('column','<aside>','</aside>'); ?>
		<section id="body"><?php echo $this->fetch($this->theme->getContentTemplate($content), ['content' => $content, 'response' => $response]); ?></section>
		<?php echo $portal->blocksArea('footer','<footer>','</footer>'); ?>
	</body>
</html>